# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: eca0423bc421eb1cc94b2b835641d179969812f509a6c1f8b9c582d71a1835e5b31b67eeff4ad55533be01f604711ca662d4816da5b27d0782212ac3a2d740f3

test:
  secret_key_base: 5691fd560cf95014a36919963cfc9c18390cfe11b121cadd458c105a5fd96985d4c3373cdff8e028c28e63700158c4aca963c4f1197c8b8bd1c3fd461071e138

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
